swagger: '2.0'
info:
    title: Communication Management Extentions
    version: 1.0.0
paths: {}
definitions:
    ExtendedAttachment:
        allOf:
            -   $ref: 'api.yml#/definitions/Attachment'
            -   type: object
                properties:
                    fileBytes:
                        type: string
                        x-tostringIgnore: true
                required:
                    - fileBytes
    ExtendedCommunicationMessage:
        allOf:
            -   $ref: 'api.yml#/definitions/CommunicationMessage'
            -   type: object
                properties:
                    result:
                        $ref: '#/definitions/Result'
                        description: Arequest results
                required:
                    - result
    Result:
        properties:
            successCount:
                type: integer
            failureCount:
                type: integer
            details:
                type: array
                items:
                    $ref: '#/definitions/Detail'
        required:
            - successCount
            - failureCount
    Detail:
        properties:
            status:
                type: string
                enum:
                    - SUCCESS
                    - ERROR
            receiver:
                $ref: 'api.yml#/definitions/Receiver'
            messageId:
                type: string
            error:
                $ref: '#/definitions/ErrorDetail'
        required:
            - status
            - receiver
    ErrorDetail:
        properties:
            code:
                type: string
            description:
                type: string
        required:
            - code
