---
langs:
    - en
emails:
    - templateKey: activationEmail
      name: "Activation email"
      subjectTemplate: {en: "Account activation"}
      emailFrom: {en: "my-company@mail.com"}
      templatePath: uaa/activation
      contextExample: |
          {
              "user": {
                "firstName": "John",
                "lastName": "Doe"
              },
              "baseUrl": "my-company.com",
              "activationKey": "myactivationkey"
          }
      contextSpec: |
          {
              "type": "object",
              "properties": {
                  "user": {
                        "type": "object",
                        "properties": {
                            "firstName": { "type": "string" },
                            "lastName": { "type": "string" }
                        }
                  },
                  "baseUrl": { "type": "string" },
                  "activationKey": { "type": "string" }
              }
          }
      contextForm: |
          {
            "form": [
               { "key": "user.firstName", "title": { "en": "First name" }, "type": "string" },
               { "key": "user.lastName", "title": { "en": "Last name" }, "type": "string" },
               { "key": "activationKey", "title": { "en": "Activation key" }, "type": "string" },
               { "key": "baseUrl", "title": { "en": "Base URL" }, "type": "string" }
            ]
          }
    - templateKey: accountCreationEmail
      name: "Account creation email"
      subjectTemplate: {en: "Account creation"}
      emailFrom: {en: "my-company@mail.com"}
      templatePath: uaa/creation
      contextExample: |
          {
              "user": {
                "firstName": "John",
                "lastName": "Doe"
              },
              "baseUrl": "my-company.com",
              "resetKey": "myresetkey"
          }
      contextSpec: |
          {
              "type": "object",
              "properties": {
                  "user": {
                        "type": "object",
                        "properties": {
                            "firstName": { "type": "string" },
                            "lastName": { "type": "string" }
                        }
                  },
                  "baseUrl": { "type": "string" },
                  "resetKey": { "type": "string" }
              }
          }
      contextForm: |
          {
            "form": [
               { "key": "user.firstName", "title": { "en": "First name" }, "type": "string" },
               { "key": "user.lastName", "title": { "en": "Last name" }, "type": "string" },
               { "key": "resetKey", "title": { "en": "Reset key" }, "type": "string" },
               { "key": "baseUrl", "title": { "en": "Base URL" }, "type": "string" }
            ]
          }
    - templateKey: passwordResetEmail
      name: "Password reset email"
      subjectTemplate: {en: "uaa password reset"}
      emailFrom: {en: "my-company@mail.com"}
      templatePath: uaa/passwordReset
      contextExample: |
          {
              "user": {
                "firstName": "John",
                "lastName": "Doe"
              },
              "baseUrl": "my-company.com",
              "resetKey": "myresetkey"
          }
      contextSpec: |
          {
              "type": "object",
              "properties": {
                  "user": {
                        "type": "object",
                        "properties": {
                            "firstName": { "type": "string" },
                            "lastName": { "type": "string" }
                        }
                  },
                  "baseUrl": { "type": "string" },
                  "resetKey": { "type": "string" }
              }
          }
      contextForm: |
          {
            "form": [
               { "key": "user.firstName", "title": { "en": "First name" }, "type": "string" },
               { "key": "user.lastName", "title": { "en": "Last name" }, "type": "string" },
               { "key": "resetKey", "title": { "en": "Reset key" }, "type": "string" },
               { "key": "baseUrl", "title": { "en": "Base URL" }, "type": "string" }
            ]
          }
